//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szt2_projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class FELHASZNALO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FELHASZNALO()
        {
            this.RENDELESEK = new HashSet<RENDELESEK>();
            this.UZENETEK = new HashSet<UZENETEK>();
            this.KEDVENCEK = new HashSet<KEDVENCEK>();
        }
    
        public decimal FELHASZNALO_ID { get; set; }
        public string NEV { get; set; }
        public string BEOSZTAS { get; set; }
        public string JELSZO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RENDELESEK> RENDELESEK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UZENETEK> UZENETEK { get; set; }
        public virtual SZEMELYES_ADATOK SZEMELYES_ADATOK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KEDVENCEK> KEDVENCEK { get; set; }
    }
}
