//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szt2_projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZEMELYES_ADATOK
    {
        public decimal FELHASZNALO_ID { get; set; }
        public string VEZETEKNEV { get; set; }
        public string KERESZTNEV { get; set; }
        public string EMAILCIM { get; set; }
        public string CIM { get; set; }
        public string TELEFONSZAM { get; set; }
    
        public virtual FELHASZNALO FELHASZNALO { get; set; }
    }
}
