//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szt2_projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class UZENETEK
    {
        public decimal UZENET_ID { get; set; }
        public decimal FELHASZNALO_ID { get; set; }
        public string SZOVEG { get; set; }
        public System.DateTime DATUM { get; set; }
        public bool IRANY { get; set; }
        public bool LATTA_E { get; set; }
    
        public virtual FELHASZNALO FELHASZNALO { get; set; }
    }
}
